### ISSUE TITLE
Illegal capture

### ISSUE THREAD

**Issue by rinvii** [martinsi26/ChessGame#38]
White bishop can capture king

![image](https://user-images.githubusercontent.com/76126859/202028870-0532b678-442d-4280-a639-63f0cd9bb602.jpeg)

![image](https://user-images.githubusercontent.com/76126859/202028967-aff3da0b-684f-4680-9365-359ffc430f7a.jpeg)

**Comment by nerenber26** [comment]
Check now works correctly
