### ISSUE TITLE
Chess Bugs 

### ISSUE THREAD

**Issue by msurur** [martinsi26/ChessGame#40]
1. You can counteract a declared check by declaring a check of your own (and vice versa). This locks you out of recurving a win condition.
2. Queen can’t move horizontally sometimes.
3. No win condition upon capturing the king.
4. Check decision cycles for the dumb AI can be infinitely recursive, and can break the game.

-Checkers Group

**Comment by nerenber26** [comment]
We added an end condition. AI should find a move or the game should be over.

**Comment by nerenber26** [comment]
Not sure about the Queen not being able to move sideways, we have not seen any problems with movement
