### ISSUE TITLE
Shogi Team Comments Beta

### ISSUE THREAD

**Issue by torresb24** [martinsi26/ChessGame#63]
On last opponent piece (King), cannot make anymore moves and must resign/restart app to end game.

Very good AI implementation when King is in check, doesn’t just make random moves

Clicked on Queen during beginning of game, game asked me to pick a promotion piece, but conditions for promotion were not fulfilled, Queen was in initial spot.

Moved pawn to end of board to promote, chose queen, new queen spawned in correct place but pawn remained in same spot throughout entire game, could not move it or take it away. In addition when promoted to queen the current queen randomly spawned to promotion tile and a rook spawned in the queens initial spot.

With only king left, made a few moves and Promotion prompt appeared. No player pieces were on the top half of the board for promotion.

Check treated as a checkmate. Got win message during check condition.

**Comment by cachola25** [comment]
We have a working stalemate now so the game should be able to end when the king has no legal moves.

Promotion issues have been fixed, it no longer prompts for promotion when it shouldn't and correctly redraws the screen when a promotion is made.

Check and checkmate have been updated.
