### ISSUE TITLE
Beta - Quarto Team

### ISSUE THREAD

**Issue by nakakura24** [martinsi26/ChessGame#64]
1. When the king is put in check, both AIs take a very long time to make a move out of check.
2. When in a stalemate, it is stuck on the opponent AI's turn, and there is no "end of game" message.
3. I put the smart AI's king in check, and I was able to move again (twice in a row).

**Comment by cachola25** [comment]
1. The AIs take a shorter amount of time to get out of check now
2. Stalemate has been implemented 
3. Smart AI has been refined and updated so this should no longer happen
