### ISSUE TITLE
Crazy Eights Team Issue

### ISSUE THREAD

**Issue by martinsi26** [martinsi26/ChessGame#66]
- Ate the AI's last pawn and was asked to pick a promotion piece. We chose bishop and it gave us our bishop back. (Got 3 bishops with no pawn making it the whole way).
- We are able to change the text box of the position log by holding down and pressing undo.
-  Tapped repeatedly on the screen and the game broke/froze.
- when promoting a pawn a new piece is drawn but the pawn is still there.

**Comment by cachola25** [comment]
Promotion issues have been fixed so it correctly redraws the screen and only prompts for promotion when it should.

The textbox has been updated so you can no longer edit it.

Haven't been able to recreate the issue of the game crashing after tapping on the screen repeatedly, but as of now, it doesn't crash when the screen is tapped repeatedly.
