### ISSUE TITLE
Uno Team

### ISSUE THREAD

**Issue by martinsi26** [martinsi26/ChessGame#67]
- When enemy king is put into check, it will stutter and take a few seconds to move
- It felt like a softlock when I stalemated the king. He wasn't in check but had nowhere to move and the game effectively stopped with his square highlighted. A stalemate message would clear that up.
- If you checkmate the enemy when you're black, it doesn't recognize

**Comment by cachola25** [comment]
- The process of getting out of check has been sped up
- Stalemate has been implemented so that game should end if a stalemate occurs
- Checkmate and stalemate work for both sides now
